# Generated by Django 4.1.7 on 2023-03-21 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_adminjobcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarnRecived', models.BooleanField()),
                ('weightOfYarn', models.IntegerField()),
                ('orderNo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.adminjobcard')),
            ],
        ),
    ]
