# Generated by Django 4.1.7 on 2023-03-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_yarn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yarn',
            old_name='yarnRecived',
            new_name='yarnReceived',
        ),
    ]
