# Generated by Django 4.1.7 on 2023-03-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_yarnrecived_yarn_yarnreceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalWeightOfWarpedYarn', models.IntegerField()),
                ('wasteCollectionWeight', models.IntegerField()),
                ('buttonToReportToSupervisor', models.CharField(max_length=100)),
                ('packageDefects', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Winding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarnReceived', models.BooleanField()),
                ('noOfCones', models.IntegerField()),
                ('sizeOfCones', models.CharField(max_length=100)),
                ('noOfDoffs', models.IntegerField()),
                ('finalWeightOfCone', models.IntegerField()),
                ('wasteCollectionWeight', models.IntegerField()),
            ],
        ),
    ]
