# Generated by Django 4.1.7 on 2023-03-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_warping_winding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weaving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarnReceived', models.BooleanField()),
                ('date', models.DateField()),
                ('loomNo', models.IntegerField()),
                ('totalPicks', models.IntegerField()),
                ('wasteCollectionWeight', models.IntegerField()),
                ('supervisor', models.CharField(max_length=100)),
                ('orderNo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.adminjobcard')),
            ],
        ),
    ]
