# Generated by Django 4.1.7 on 2023-03-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_repairing_warping_orderno_winding_orderno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='orderNo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.adminjobcard'),
        ),
    ]
