# Generated by Django 4.1.7 on 2023-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_yarn_orderno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.adminjobcard'),
        ),
        migrations.AlterField(
            model_name='warping',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.adminjobcard'),
        ),
        migrations.AlterField(
            model_name='weaving',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.adminjobcard'),
        ),
        migrations.AlterField(
            model_name='winding',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.adminjobcard'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.adminjobcard'),
        ),
    ]
