# Generated by Django 4.1.7 on 2023-03-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_checking_orderno_alter_warping_orderno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='id',
        ),
        migrations.AlterField(
            model_name='yarn',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.adminjobcard'),
        ),
    ]
