# Generated by Django 4.1.7 on 2023-03-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_yarn_id_alter_yarn_orderno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winding',
            name='id',
        ),
        migrations.AddField(
            model_name='winding',
            name='defects',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='winding',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.adminjobcard'),
        ),
    ]
