# Generated by Django 4.1.7 on 2023-03-22 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_rename_weaving_looming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looming',
            name='id',
        ),
        migrations.RemoveField(
            model_name='looming',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='warping',
            name='id',
        ),
        migrations.AddField(
            model_name='looming',
            name='target',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='adminjobcard',
            name='target',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='looming',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.adminjobcard'),
        ),
        migrations.AlterField(
            model_name='warping',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.adminjobcard'),
        ),
    ]
