# Generated by Django 4.1.7 on 2023-03-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_repairing_id_repairing_orderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminjobcard',
            name='isYarningDone',
            field=models.BooleanField(default=False),
        ),
    ]
