# Generated by Django 4.1.7 on 2023-03-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_adminjobcard_isyarningdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminjobcard',
            name='isCheckingDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminjobcard',
            name='isLoomingDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminjobcard',
            name='isRepairingDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminjobcard',
            name='isWarpingDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminjobcard',
            name='isWindingDone',
            field=models.BooleanField(default=False),
        ),
    ]
